import type { PendingStylistApplicationsResponse } from "@/models/stylistApplication"

export const MOCK_PENDING_STYLIST_APPLICATIONS: PendingStylistApplicationsResponse =
  [
    {
      id: "1",
      userId: "user-1",
      businessName: "Styled by Jane",
      gender: "Female",
      location: "New York, NY",
      instagramHandle: "@jane.styles",
      facebookHandle: "Styled by Jane",
      tiktokHandle: "@janestyles",
      linkedInUrl: "https://linkedin.com/in/jane-stylist",
      experience: "7 years",
      platformSource: "Instagram",
      pushNotification: true,
      speciality: [
        "High fashion/editorial",
        "Special events/weddings",
        "Capsule Wardrobes",
      ],
      recommendShops: ["Macy's", "Zara", "Nordstrom"],
      bio: "Wardrobe and personal stylist focused on events and premium looks.",
      imageUrl:
        "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=320&h=320&fit=crop&crop=faces",
      isVerified: false,
      available: true,
      bookingNotification: true,
      bookingSms: false,
      bookingEmail: true,
      bookingReminderNotification: true,
      bookingReminderSms: false,
      bookingReminderEmail: true,
      messageNotification: true,
      messageSms: false,
      messageEmail: true,
      reviewNotification: true,
      reviewSms: false,
      reviewEmail: true,
      availabilityNotification: true,
      languageSpoken: ["English"],
      createdAt: "2026-03-01T10:20:00.000Z",
      updatedAt: "2026-03-20T12:00:00.000Z",
      user: {
        id: "user-1",
        email: "jane.smith@example.com",
        firstName: "Jane",
        lastName: "Smith",
      },
      firstName: "Jane",
      lastName: "Smith",
      email: "jane.smith@example.com",
    },
  ]
