import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/lib/provider";
import { MswProvider } from "@/components/msw-provider";
import { Toaster } from "@/components/ui/sonner"
import localFont from 'next/font/local'

const lufga = localFont({
  src: [
    {
      path: '../../public/lufga/LufgaMedium.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/lufga/LufgaSemiBold.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/lufga/LufgaBold.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/lufga/LufgaExtraBold.woff',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../../public/lufga/LufgaBlack.woff',
      weight: '900',
      style: 'normal',
    },
  ],
})

const satoshi = localFont({
  src: [
    {
      path: '../../public/fonts/SatoshiRegular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/SatoshiBold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/SatoshiBlack.otf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-satoshi-family',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Instastylin Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={satoshi.variable}>
      <body
        className={`${lufga.className} antialiased`}
      >
        <MswProvider>
          <Providers>
            {children}
          </Providers>
        </MswProvider>
        <Toaster />
      </body>
    </html>
  );
}
